### ISSUE TITLE
[META] Boilerplate

### ISSUE THREAD

**Issue by nakajimayoshi** [owddm/discord-bot#1]
# Boilerplate

- [x] Architecture 
- [x] Integrate Slash command API 
- [ ] Make contributing docs 
- [x] Add README 
- [x] Add PR Template 
- [x] Add CHANGELOG 
- [ ] Add Workflows / Webhooks
